<!doctype html><html lang=en dir=auto><head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Python Fundamentals: Understanding Error Handling (Part 6) | Quick Reference</title>
<meta name=keywords content="Python,Programming,Error Handling,Tutorial"><meta name=description content="Learn about error handling in Python with this comprehensive guide, part of our series on Python programming."><meta name=author content="Nirajan Khatiwada"><link rel=canonical href=http://localhost:1313/posts/pages/python/python_error_handeling/><link crossorigin=anonymous href=/assets/css/stylesheet.fc220c15db4aef0318bbf30adc45d33d4d7c88deff3238b23eb255afdc472ca6.css integrity="sha256-/CIMFdtK7wMYu/MK3EXTPU18iN7/MjiyPrJVr9xHLKY=" rel="preload stylesheet" as=style><link rel=icon href=http://localhost:1313/images/icon.png><link rel=icon type=image/png sizes=16x16 href=http://localhost:1313/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=http://localhost:1313/favicon-32x32.png><link rel=apple-touch-icon href=http://localhost:1313/apple-touch-icon.png><link rel=mask-icon href=http://localhost:1313/safari-pinned-tab.svg><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><link rel=alternate hreflang=en href=http://localhost:1313/posts/pages/python/python_error_handeling/><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--code-block-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><meta property="og:title" content="Python Fundamentals: Understanding Error Handling (Part 6)"><meta property="og:description" content="Learn about error handling in Python with this comprehensive guide, part of our series on Python programming."><meta property="og:type" content="article"><meta property="og:url" content="http://localhost:1313/posts/pages/python/python_error_handeling/"><meta property="og:image" content="http://localhost:1313/images/python.png"><meta property="article:section" content="posts"><meta property="article:published_time" content="2024-11-18T00:00:00+00:00"><meta property="article:modified_time" content="2024-11-18T00:00:00+00:00"><meta property="og:site_name" content="Quick Reference"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="http://localhost:1313/images/python.png"><meta name=twitter:title content="Python Fundamentals: Understanding Error Handling (Part 6)"><meta name=twitter:description content="Learn about error handling in Python with this comprehensive guide, part of our series on Python programming."><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Posts","item":"http://localhost:1313/posts/"},{"@type":"ListItem","position":2,"name":"Python Fundamentals: Understanding Error Handling (Part 6)","item":"http://localhost:1313/posts/pages/python/python_error_handeling/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Python Fundamentals: Understanding Error Handling (Part 6)","name":"Python Fundamentals: Understanding Error Handling (Part 6)","description":"Learn about error handling in Python with this comprehensive guide, part of our series on Python programming.","keywords":["Python","Programming","Error Handling","Tutorial"],"articleBody":"Python Fundamentals: Understanding Error Handling In Python programming, error handling is an essential concept that allows you to gracefully manage exceptions and errors that may occur during program execution. By handling errors effectively, you can prevent your program from crashing and provide meaningful feedback to users. In this guide, we will explore the fundamentals of error handling in Python, including exceptions, try-except blocks, and best practices.\n1. Exceptions In Python, exceptions are events that occur during the execution of a program that disrupt the normal flow of code. When an exception occurs, the interpreter raises an exception object that can be caught and handled by the program. Exceptions can be caused by various reasons, such as invalid input, file not found, or division by zero.\n2.What May Cause Exceptions Exceptions can be caused by various reasons, such as:\nDivision by zero Invalid input File not found Syntax errors Out of Index of list, tuple , String Key Error in dictionary 3.Types of Exceptions Commonly used exceptions in Python include:\nZeroDivisionError: Raised when division or modulo by zero occurs. ValueError: Raised when a function receives an argument of the correct type but an inappropriate value. TypeError: Raised when an operation or function is applied to an object of an inappropriate type. IndexError: Raised when a sequence subscript is out of range. KeyError: Raised when a dictionary key is not found. SyntaxError: Raised when the parser encounters a syntax error. Note: All exceptions in Python are subclasses of the Exception class.\n3.Handling Exceptions To handle exceptions in Python, you can use the try-except block, which allows you to catch and handle exceptions gracefully. The try block contains the code that may raise an exception, and the except block handles the exception if it occurs.The program control will transfer the control to the except block if any exception occurs in the try block but if there is not exception then the control will not transfer to the except block.\n4.1. Using try-except Block Here’s an example of using the try-except block to handle exceptions in Python:\nsyntax:\ntry: # Code that may raise an exception except ExceptionType as e: # Handle the exception Example:\ntry: x = 10 / 0 except Exception as e: print(\"Error: Division by zero\") Output:\nError: Division by zero Note: if you don’t know the type of exception you can use Exception to catch all exceptions.\nIf you dont handel exception then it will show error and stop the program.\n4.2. Finally Block The finally block is used to execute code that should always run, regardless of whether an exception occurs or not. The finally block is typically used to release resources or clean up operations that need to be performed after the try block, regardless of the outcome Any how the finally block will run. if yout return from the try block then also the finally block will run.\nsyntax:\ntry: # Code that may raise an exception except ExceptionType as e: # Handle the exception finally: # Code that always runs Example:\ntry: x = 10 / 0 except Exception as e: print(\"Error: Division by zero\") finally: print(\"Cleanup code\") Output:\nError: Division by zero\rCleanup code 3.5. Raising Exceptions You can raise exceptions in Python using the raise statement. This allows you to create custom exceptions and raise them when needed. You can also raise built-in exceptions to indicate errors or exceptional conditions.\nsyntax:\nraise ExceptionType(\"Error message\") Example:\nx = -1 if x \u003c 0: raise ValueError(\"Value cannot be negative\") Output:\nValueError: Value cannot be negative 3.6. Multiple except Blocks You can use multiple except blocks to handle different types of exceptions in Python. This allows you to catch and handle specific exceptions based on their type.\nsyntax:\ntry: # Code that may raise an exception except ExceptionType1 as e: # Handle ExceptionType1 except ExceptionType2 as e: # Handle ExceptionType2 Example:\ntry: x = 10 / 0 except ZeroDivisionError as e: print(\"Error: Division by zero\") except ValueError as e: print(\"Error: Invalid value\") Output:\nError: Division by zero 3.7. Custom Exceptions You can create custom exceptions in Python by defining a new exception class that inherits from the Exception class. Custom exceptions allow you to define specific error conditions for your application and raise them when needed.\nsyntax:\nclass CustomException(Exception): pass Example:\n#Will read about class in oop section class CustomError(Exception): def __init__(self,message,value): self.message=message self.value=value def __str__(self): return f\"{self.message}\\nError code:{self.value}\" try: x = -1 if x \u003c 0: raise CustomError(\"Value cannot be negative\",1001) except CustomError as e: print(e) Note: Custom exceptions should inherit from the Exception class or one of its subclasses. You can simply use:\ntry: #code except: #code try: #code except Exception as e: #code try: #code except Exception: #code try: #code except: #code finally: #code ","wordCount":"790","inLanguage":"en","image":"http://localhost:1313/images/python.png","datePublished":"2024-11-18T00:00:00Z","dateModified":"2024-11-18T00:00:00Z","author":{"@type":"Person","name":"Nirajan Khatiwada"},"mainEntityOfPage":{"@type":"WebPage","@id":"http://localhost:1313/posts/pages/python/python_error_handeling/"},"publisher":{"@type":"Organization","name":"Quick Reference","logo":{"@type":"ImageObject","url":"http://localhost:1313/images/icon.png"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=http://localhost:1313/ accesskey=h title="Quick Reference (Alt + H)">Quick Reference</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=http://localhost:1313/categories/ title=Categories><span>Categories</span></a></li><li><a href=http://localhost:1313/tags/ title=Tags><span>Tags</span></a></li><li><a href=http://localhost:1313/search title="Search (Alt + /)" accesskey=/><span>Search</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=http://localhost:1313/>Home</a>&nbsp;»&nbsp;<a href=http://localhost:1313/posts/>Posts</a></div><h1 class="post-title entry-hint-parent">Python Fundamentals: Understanding Error Handling (Part 6)</h1><div class=post-description>Learn about error handling in Python with this comprehensive guide, part of our series on Python programming.</div><div class=post-meta><span title='2024-11-18 00:00:00 +0000 UTC'>November 18, 2024</span>&nbsp;·&nbsp;4 min&nbsp;·&nbsp;790 words&nbsp;·&nbsp;Nirajan Khatiwada&nbsp;|&nbsp;<a href=https://github.com/nirajan-khatiwada/quick-reference/tree/main/content/posts/pages/python/python_error_handeling.md rel="noopener noreferrer" target=_blank>Suggest Changes</a></div></header><div class=toc><details><summary accesskey=c title="(Alt + C)"><span class=details>Table of Contents</span></summary><div class=inner><nav id=TableOfContents><ul><li><a href=#1-exceptions>1. Exceptions</a></li><li><a href=#2what-may-cause-exceptions>2.What May Cause Exceptions</a></li><li><a href=#3types-of-exceptions>3.Types of Exceptions</a></li><li><a href=#3handling-exceptions>3.Handling Exceptions</a><ul><li><a href=#41-using-try-except-block>4.1. Using <code>try-except</code> Block</a></li><li><a href=#42-finally-block>4.2. Finally Block</a></li><li><a href=#35-raising-exceptions>3.5. Raising Exceptions</a></li><li><a href=#36-multiple-except-blocks>3.6. Multiple <code>except</code> Blocks</a></li><li><a href=#37-custom-exceptions>3.7. Custom Exceptions</a></li></ul></li></ul></nav></div></details></div><div class=post-content><h1 id=python-fundamentals-understanding-error-handling>Python Fundamentals: Understanding Error Handling<a hidden class=anchor aria-hidden=true href=#python-fundamentals-understanding-error-handling>#</a></h1><p>In Python programming, error handling is an essential concept that allows you to gracefully manage exceptions and errors that may occur during program execution. By handling errors effectively, you can prevent your program from crashing and provide meaningful feedback to users. In this guide, we will explore the fundamentals of error handling in Python, including exceptions, try-except blocks, and best practices.</p><h2 id=1-exceptions>1. Exceptions<a hidden class=anchor aria-hidden=true href=#1-exceptions>#</a></h2><p>In Python, exceptions are events that occur during the execution of a program that disrupt the normal flow of code. When an exception occurs, the interpreter raises an exception object that can be caught and handled by the program. Exceptions can be caused by various reasons, such as invalid input, file not found, or division by zero.</p><h2 id=2what-may-cause-exceptions>2.What May Cause Exceptions<a hidden class=anchor aria-hidden=true href=#2what-may-cause-exceptions>#</a></h2><p>Exceptions can be caused by various reasons, such as:</p><ul><li>Division by zero</li><li>Invalid input</li><li>File not found</li><li>Syntax errors</li><li>Out of Index of list, tuple , String</li><li>Key Error in dictionary</li></ul><h2 id=3types-of-exceptions>3.Types of Exceptions<a hidden class=anchor aria-hidden=true href=#3types-of-exceptions>#</a></h2><p>Commonly used exceptions in Python include:</p><ul><li><code>ZeroDivisionError</code>: Raised when division or modulo by zero occurs.</li><li><code>ValueError</code>: Raised when a function receives an argument of the correct type but an inappropriate value.</li><li><code>TypeError</code>: Raised when an operation or function is applied to an object of an inappropriate type.</li><li><code>IndexError</code>: Raised when a sequence subscript is out of range.</li><li><code>KeyError</code>: Raised when a dictionary key is not found.</li><li><code>SyntaxError</code>: Raised when the parser encounters a syntax error.</li></ul><blockquote><p>Note: All exceptions in Python are subclasses of the <code>Exception</code> class.</p></blockquote><h2 id=3handling-exceptions>3.Handling Exceptions<a hidden class=anchor aria-hidden=true href=#3handling-exceptions>#</a></h2><p>To handle exceptions in Python, you can use the <code>try-except</code> block, which allows you to catch and handle exceptions gracefully. The <code>try</code> block contains the code that may raise an exception, and the <code>except</code> block handles the exception if it occurs.The program control will transfer the control to the except block if any exception occurs in the try block but if there is not exception then the control will not transfer to the except block.</p><h3 id=41-using-try-except-block>4.1. Using <code>try-except</code> Block<a hidden class=anchor aria-hidden=true href=#41-using-try-except-block>#</a></h3><p>Here&rsquo;s an example of using the <code>try-except</code> block to handle exceptions in Python:</p><p>syntax:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e># Code that may raise an exception</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> ExceptionType <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    <span style=color:#75715e># Handle the exception</span>
</span></span></code></pre></div><p>Example:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    x <span style=color:#f92672>=</span> <span style=color:#ae81ff>10</span> <span style=color:#f92672>/</span> <span style=color:#ae81ff>0</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> <span style=color:#a6e22e>Exception</span> <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    print(<span style=color:#e6db74>&#34;Error: Division by zero&#34;</span>)
</span></span></code></pre></div><p>Output:</p><pre tabindex=0><code>Error: Division by zero
</code></pre><blockquote><p>Note: if you don&rsquo;t know the type of exception you can use <code>Exception</code> to catch all exceptions.</p><blockquote><p>If you dont handel exception then it will show error and stop the program.</p></blockquote></blockquote><h3 id=42-finally-block>4.2. Finally Block<a hidden class=anchor aria-hidden=true href=#42-finally-block>#</a></h3><p>The <code>finally</code> block is used to execute code that should always run, regardless of whether an exception occurs or not. The <code>finally</code> block is typically used to release resources or clean up operations that need to be performed after the <code>try</code> block, regardless of the outcome Any how the finally block will run. if yout return from the try block then also the finally block will run.</p><p>syntax:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e># Code that may raise an exception</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> ExceptionType <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    <span style=color:#75715e># Handle the exception</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>finally</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e># Code that always runs</span>
</span></span></code></pre></div><p>Example:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    x <span style=color:#f92672>=</span> <span style=color:#ae81ff>10</span> <span style=color:#f92672>/</span> <span style=color:#ae81ff>0</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> <span style=color:#a6e22e>Exception</span> <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    print(<span style=color:#e6db74>&#34;Error: Division by zero&#34;</span>)
</span></span><span style=display:flex><span><span style=color:#66d9ef>finally</span>:
</span></span><span style=display:flex><span>    print(<span style=color:#e6db74>&#34;Cleanup code&#34;</span>)
</span></span></code></pre></div><p>Output:</p><pre tabindex=0><code>Error: Division by zero
Cleanup code
</code></pre><h3 id=35-raising-exceptions>3.5. Raising Exceptions<a hidden class=anchor aria-hidden=true href=#35-raising-exceptions>#</a></h3><p>You can raise exceptions in Python using the <code>raise</code> statement. This allows you to create custom exceptions and raise them when needed. You can also raise built-in exceptions to indicate errors or exceptional conditions.</p><p>syntax:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>raise</span> ExceptionType(<span style=color:#e6db74>&#34;Error message&#34;</span>)
</span></span></code></pre></div><p>Example:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span>x <span style=color:#f92672>=</span> <span style=color:#f92672>-</span><span style=color:#ae81ff>1</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>if</span> x <span style=color:#f92672>&lt;</span> <span style=color:#ae81ff>0</span>:
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>raise</span> <span style=color:#a6e22e>ValueError</span>(<span style=color:#e6db74>&#34;Value cannot be negative&#34;</span>)
</span></span></code></pre></div><p>Output:</p><pre tabindex=0><code>ValueError: Value cannot be negative
</code></pre><h3 id=36-multiple-except-blocks>3.6. Multiple <code>except</code> Blocks<a hidden class=anchor aria-hidden=true href=#36-multiple-except-blocks>#</a></h3><p>You can use multiple <code>except</code> blocks to handle different types of exceptions in Python. This allows you to catch and handle specific exceptions based on their type.</p><p>syntax:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e># Code that may raise an exception</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> ExceptionType1 <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    <span style=color:#75715e># Handle ExceptionType1</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> ExceptionType2 <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    <span style=color:#75715e># Handle ExceptionType2</span>
</span></span></code></pre></div><p>Example:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    x <span style=color:#f92672>=</span> <span style=color:#ae81ff>10</span> <span style=color:#f92672>/</span> <span style=color:#ae81ff>0</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> <span style=color:#a6e22e>ZeroDivisionError</span> <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    print(<span style=color:#e6db74>&#34;Error: Division by zero&#34;</span>)
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> <span style=color:#a6e22e>ValueError</span> <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    print(<span style=color:#e6db74>&#34;Error: Invalid value&#34;</span>)
</span></span></code></pre></div><p>Output:</p><pre tabindex=0><code>Error: Division by zero
</code></pre><h3 id=37-custom-exceptions>3.7. Custom Exceptions<a hidden class=anchor aria-hidden=true href=#37-custom-exceptions>#</a></h3><p>You can create custom exceptions in Python by defining a new exception class that inherits from the <code>Exception</code> class. Custom exceptions allow you to define specific error conditions for your application and raise them when needed.</p><p>syntax:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>class</span> <span style=color:#a6e22e>CustomException</span>(<span style=color:#a6e22e>Exception</span>):
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>pass</span>
</span></span></code></pre></div><p>Example:</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#75715e>#Will read about class in oop section</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>class</span> <span style=color:#a6e22e>CustomError</span>(<span style=color:#a6e22e>Exception</span>):
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>def</span> __init__(self,message,value):
</span></span><span style=display:flex><span>        self<span style=color:#f92672>.</span>message<span style=color:#f92672>=</span>message
</span></span><span style=display:flex><span>        self<span style=color:#f92672>.</span>value<span style=color:#f92672>=</span>value
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>def</span> __str__(self):
</span></span><span style=display:flex><span>        <span style=color:#66d9ef>return</span> <span style=color:#e6db74>f</span><span style=color:#e6db74>&#34;</span><span style=color:#e6db74>{</span>self<span style=color:#f92672>.</span>message<span style=color:#e6db74>}</span><span style=color:#ae81ff>\n</span><span style=color:#e6db74>Error code:</span><span style=color:#e6db74>{</span>self<span style=color:#f92672>.</span>value<span style=color:#e6db74>}</span><span style=color:#e6db74>&#34;</span>
</span></span><span style=display:flex><span>    
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    x <span style=color:#f92672>=</span> <span style=color:#f92672>-</span><span style=color:#ae81ff>1</span>
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>if</span> x <span style=color:#f92672>&lt;</span> <span style=color:#ae81ff>0</span>:
</span></span><span style=display:flex><span>        <span style=color:#66d9ef>raise</span> CustomError(<span style=color:#e6db74>&#34;Value cannot be negative&#34;</span>,<span style=color:#ae81ff>1001</span>)
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> CustomError <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    print(e)
</span></span></code></pre></div><blockquote><p>Note: Custom exceptions should inherit from the <code>Exception</code> class or one of its subclasses.
You can simply use:</p></blockquote><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> <span style=color:#a6e22e>Exception</span> <span style=color:#66d9ef>as</span> e:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span> <span style=color:#a6e22e>Exception</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>try</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>except</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>finally</span>:
</span></span><span style=display:flex><span>    <span style=color:#75715e>#code</span>
</span></span></code></pre></div></div><footer class=post-footer><ul class=post-tags><li><a href=http://localhost:1313/tags/python/>Python</a></li><li><a href=http://localhost:1313/tags/programming/>Programming</a></li><li><a href=http://localhost:1313/tags/error-handling/>Error Handling</a></li><li><a href=http://localhost:1313/tags/tutorial/>Tutorial</a></li></ul><nav class=paginav><a class=prev href=http://localhost:1313/posts/pages/python/python_advanced_topics/><span class=title>« Prev</span><br><span>Python Fundamentals: Packages, Generators, and Decorators (Part 7)</span>
</a><a class=next href=http://localhost:1313/posts/pages/python/python_function/><span class=title>Next »</span><br><span>Python Fundamentals: Understanding Functions (Part 5)</span></a></nav><ul class=share-buttons><li><a target=_blank rel="noopener noreferrer" aria-label="share Python Fundamentals: Understanding Error Handling (Part 6) on x" href="https://x.com/intent/tweet/?text=Python%20Fundamentals%3a%20Understanding%20Error%20Handling%20%28Part%206%29&amp;url=http%3a%2f%2flocalhost%3a1313%2fposts%2fpages%2fpython%2fpython_error_handeling%2f&amp;hashtags=Python%2cProgramming%2cErrorHandling%2cTutorial"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M512 62.554V449.446C512 483.97 483.97 512 449.446 512H62.554C28.03 512 0 483.97.0 449.446V62.554C0 28.03 28.029.0 62.554.0H449.446C483.971.0 512 28.03 512 62.554zM269.951 190.75 182.567 75.216H56L207.216 272.95 63.9 436.783h61.366L235.9 310.383l96.667 126.4H456L298.367 228.367l134-153.151H371.033zM127.633 110h36.468l219.38 290.065H349.5z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Python Fundamentals: Understanding Error Handling (Part 6) on linkedin" href="https://www.linkedin.com/shareArticle?mini=true&amp;url=http%3a%2f%2flocalhost%3a1313%2fposts%2fpages%2fpython%2fpython_error_handeling%2f&amp;title=Python%20Fundamentals%3a%20Understanding%20Error%20Handling%20%28Part%206%29&amp;summary=Python%20Fundamentals%3a%20Understanding%20Error%20Handling%20%28Part%206%29&amp;source=http%3a%2f%2flocalhost%3a1313%2fposts%2fpages%2fpython%2fpython_error_handeling%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM160.461 423.278V197.561h-75.04v225.717h75.04zm270.539.0V293.839c0-69.333-37.018-101.586-86.381-101.586-39.804.0-57.634 21.891-67.617 37.266v-31.958h-75.021c.995 21.181.0 225.717.0 225.717h75.02V297.222c0-6.748.486-13.492 2.474-18.315 5.414-13.475 17.767-27.434 38.494-27.434 27.135.0 38.007 20.707 38.007 51.037v120.768H431zM123.448 88.722C97.774 88.722 81 105.601 81 127.724c0 21.658 16.264 39.002 41.455 39.002h.484c26.165.0 42.452-17.344 42.452-39.002-.485-22.092-16.241-38.954-41.943-39.002z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Python Fundamentals: Understanding Error Handling (Part 6) on reddit" href="https://reddit.com/submit?url=http%3a%2f%2flocalhost%3a1313%2fposts%2fpages%2fpython%2fpython_error_handeling%2f&title=Python%20Fundamentals%3a%20Understanding%20Error%20Handling%20%28Part%206%29"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM446 265.638c0-22.964-18.616-41.58-41.58-41.58-11.211.0-21.361 4.457-28.841 11.666-28.424-20.508-67.586-33.757-111.204-35.278l18.941-89.121 61.884 13.157c.756 15.734 13.642 28.29 29.56 28.29 16.407.0 29.706-13.299 29.706-29.701.0-16.403-13.299-29.702-29.706-29.702-11.666.0-21.657 6.792-26.515 16.578l-69.105-14.69c-1.922-.418-3.939-.042-5.585 1.036-1.658 1.073-2.811 2.761-3.224 4.686l-21.152 99.438c-44.258 1.228-84.046 14.494-112.837 35.232-7.468-7.164-17.589-11.591-28.757-11.591-22.965.0-41.585 18.616-41.585 41.58.0 16.896 10.095 31.41 24.568 37.918-.639 4.135-.99 8.328-.99 12.576.0 63.977 74.469 115.836 166.33 115.836s166.334-51.859 166.334-115.836c0-4.218-.347-8.387-.977-12.493 14.564-6.47 24.735-21.034 24.735-38.001zM326.526 373.831c-20.27 20.241-59.115 21.816-70.534 21.816-11.428.0-50.277-1.575-70.522-21.82-3.007-3.008-3.007-7.882.0-10.889 3.003-2.999 7.882-3.003 10.885.0 12.777 12.781 40.11 17.317 59.637 17.317 19.522.0 46.86-4.536 59.657-17.321 3.016-2.999 7.886-2.995 10.885.008 3.008 3.011 3.003 7.882-.008 10.889zm-5.23-48.781c-16.373.0-29.701-13.324-29.701-29.698.0-16.381 13.328-29.714 29.701-29.714 16.378.0 29.706 13.333 29.706 29.714.0 16.374-13.328 29.698-29.706 29.698zM160.91 295.348c0-16.381 13.328-29.71 29.714-29.71 16.369.0 29.689 13.329 29.689 29.71.0 16.373-13.32 29.693-29.689 29.693-16.386.0-29.714-13.32-29.714-29.693z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Python Fundamentals: Understanding Error Handling (Part 6) on facebook" href="https://facebook.com/sharer/sharer.php?u=http%3a%2f%2flocalhost%3a1313%2fposts%2fpages%2fpython%2fpython_error_handeling%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H342.978V319.085h66.6l12.672-82.621h-79.272v-53.617c0-22.603 11.073-44.636 46.58-44.636H425.6v-70.34s-32.71-5.582-63.982-5.582c-65.288.0-107.96 39.569-107.96 111.204v62.971h-72.573v82.621h72.573V512h-191.104c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Python Fundamentals: Understanding Error Handling (Part 6) on whatsapp" href="https://api.whatsapp.com/send?text=Python%20Fundamentals%3a%20Understanding%20Error%20Handling%20%28Part%206%29%20-%20http%3a%2f%2flocalhost%3a1313%2fposts%2fpages%2fpython%2fpython_error_handeling%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentcolor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zm-58.673 127.703c-33.842-33.881-78.847-52.548-126.798-52.568-98.799.0-179.21 80.405-179.249 179.234-.013 31.593 8.241 62.428 23.927 89.612l-25.429 92.884 95.021-24.925c26.181 14.28 55.659 21.807 85.658 21.816h.074c98.789.0 179.206-80.413 179.247-179.243.018-47.895-18.61-92.93-52.451-126.81zM263.976 403.485h-.06c-26.734-.01-52.954-7.193-75.828-20.767l-5.441-3.229-56.386 14.792 15.05-54.977-3.542-5.637c-14.913-23.72-22.791-51.136-22.779-79.287.033-82.142 66.867-148.971 149.046-148.971 39.793.014 77.199 15.531 105.329 43.692 28.128 28.16 43.609 65.592 43.594 105.4-.034 82.149-66.866 148.983-148.983 148.984zm81.721-111.581c-4.479-2.242-26.499-13.075-30.604-14.571-4.105-1.495-7.091-2.241-10.077 2.241-2.986 4.483-11.569 14.572-14.182 17.562-2.612 2.988-5.225 3.364-9.703 1.12-4.479-2.241-18.91-6.97-36.017-22.23C231.8 264.15 222.81 249.484 220.198 245s-.279-6.908 1.963-9.14c2.016-2.007 4.48-5.232 6.719-7.847 2.24-2.615 2.986-4.484 4.479-7.472 1.493-2.99.747-5.604-.374-7.846-1.119-2.241-10.077-24.288-13.809-33.256-3.635-8.733-7.327-7.55-10.077-7.688-2.609-.13-5.598-.158-8.583-.158-2.986.0-7.839 1.121-11.944 5.604-4.105 4.484-15.675 15.32-15.675 37.364.0 22.046 16.048 43.342 18.287 46.332 2.24 2.99 31.582 48.227 76.511 67.627 10.685 4.615 19.028 7.371 25.533 9.434 10.728 3.41 20.492 2.929 28.209 1.775 8.605-1.285 26.499-10.833 30.231-21.295 3.732-10.464 3.732-19.431 2.612-21.298-1.119-1.869-4.105-2.99-8.583-5.232z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Python Fundamentals: Understanding Error Handling (Part 6) on telegram" href="https://telegram.me/share/url?text=Python%20Fundamentals%3a%20Understanding%20Error%20Handling%20%28Part%206%29&amp;url=http%3a%2f%2flocalhost%3a1313%2fposts%2fpages%2fpython%2fpython_error_handeling%2f"><svg viewBox="2 2 28 28" height="30" width="30" fill="currentcolor"><path d="M26.49 29.86H5.5a3.37 3.37.0 01-2.47-1 3.35 3.35.0 01-1-2.47V5.48A3.36 3.36.0 013 3 3.37 3.37.0 015.5 2h21A3.38 3.38.0 0129 3a3.36 3.36.0 011 2.46V26.37a3.35 3.35.0 01-1 2.47 3.38 3.38.0 01-2.51 1.02zm-5.38-6.71a.79.79.0 00.85-.66L24.73 9.24a.55.55.0 00-.18-.46.62.62.0 00-.41-.17q-.08.0-16.53 6.11a.59.59.0 00-.41.59.57.57.0 00.43.52l4 1.24 1.61 4.83a.62.62.0 00.63.43.56.56.0 00.4-.17L16.54 20l4.09 3A.9.9.0 0021.11 23.15zM13.8 20.71l-1.21-4q8.72-5.55 8.78-5.55c.15.0.23.0.23.16a.18.18.0 010 .06s-2.51 2.3-7.52 6.8z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Python Fundamentals: Understanding Error Handling (Part 6) on ycombinator" href="https://news.ycombinator.com/submitlink?t=Python%20Fundamentals%3a%20Understanding%20Error%20Handling%20%28Part%206%29&u=http%3a%2f%2flocalhost%3a1313%2fposts%2fpages%2fpython%2fpython_error_handeling%2f"><svg width="30" height="30" viewBox="0 0 512 512" fill="currentcolor" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"><path d="M449.446.0C483.971.0 512 28.03 512 62.554V449.446C512 483.97 483.97 512 449.446 512H62.554C28.03 512 0 483.97.0 449.446V62.554C0 28.03 28.029.0 62.554.0H449.446zM183.8767 87.9921h-62.034L230.6673 292.4508V424.0079h50.6655V292.4508L390.1575 87.9921H328.1233L256 238.2489z"/></svg></a></li></ul></footer></article></main><footer class=footer><span>&copy; 2024 <a href=http://localhost:1313/>Quick Reference</a></span> ·</footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg>
</a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script><script>document.querySelectorAll("pre > code").forEach(e=>{const n=e.parentNode.parentNode,t=document.createElement("button");t.classList.add("copy-code"),t.innerHTML="copy";function s(){t.innerHTML="copied!",setTimeout(()=>{t.innerHTML="copy"},2e3)}t.addEventListener("click",t=>{if("clipboard"in navigator){navigator.clipboard.writeText(e.textContent),s();return}const n=document.createRange();n.selectNodeContents(e);const o=window.getSelection();o.removeAllRanges(),o.addRange(n);try{document.execCommand("copy"),s()}catch{}o.removeRange(n)}),n.classList.contains("highlight")?n.appendChild(t):n.parentNode.firstChild==n||(e.parentNode.parentNode.parentNode.parentNode.parentNode.nodeName=="TABLE"?e.parentNode.parentNode.parentNode.parentNode.parentNode.appendChild(t):e.parentNode.appendChild(t))})</script></body></html>